{% set version = "2.23-26" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-kernsmooth
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/KernSmooth_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/KernSmooth/KernSmooth_{{ version }}.tar.gz
  sha256: b465bdac197f7faa787e625412ae03d1b7c2c134b1c924cfeb775faf9c4da73e

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - libblas
  run:
    - r-base

test:
  commands:
    - $R -e "library('KernSmooth')"           # [not win]
    - "\"%R%\" -e \"library('KernSmooth')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=KernSmooth
  dev_url: https://github.com/cran/kernsmooth
  license: Unlimited
  summary: 'Functions for kernel smoothing (and density estimation) corresponding to the book: Wand, M.P. and Jones, M.C. (1995) "Kernel Smoothing".'
  license_family: Other
  license_file:
    - LICENSE-UNLIMITED

extra:
  recipe-maintainers:
    - conda-forge/r
