appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: C6blJfr1Rnq0Q0BF8tLq1VjR6nPFSy45050ADOW1to+m92xrAjTIbctjTRDPrRTRLhE6/jGBQTRkfJbWLCN0VJU3sGEzQS+HIniBEFSP2RoKHoZxN3lw/zYaUvSBZXa7TRIdbkJvc46dSRIugkrAPsXWJ2wTS0yWifd1lT3RkrfmMZEgglzul52fD8DL1FAX3BrRg/vVqcoYOW+7f16U5JuY4uKpqQBkm8NsemwrLFYPjoHVKT6M+sNEeMrTq0K4sRZFszHV9IlPs/JqvBYpkM/jRgXVn4CPgq5PxL0heRG0Cba6+7/5hJ4cR/etp7JvczNixFUejvOPm248imFYLSThGh3XYHB8OKLY2NinM0W32+9bSO96hAwPDBK8UTRozBsNf+OrJo2iYeAdQVwUemyVn44fOQ7vPt0KgwOFcOdQX28ta+uKCYXxd58MlrM2wJ9WTbRMRzJCNdWnPwOD9k6ps/rGIZDERgSxCoXjgUOuDIejO3FUmhJAshin0SRkZWKcmqQHWF4sODLOy7VIxXo8AZS2dxlrLLfxgcCKUazDqgvqPnSHQaiIcgEQK7K17TtPM/c5ZH0ugdSOjKnuduexPbYZJ93l3rhZkv73wKvh66OkkXJA8nh89XAS3mThkFiwAZlvcWve12X1l/Gv2Q9jLuoWZlsYsABnjgiXbCs=}
